import mrna from './mrna';

describe('mrna', () => {
	it('should pass sample test', () => {
		const sampleInput = 'MA\n';
		const expected = '12';
		expect(mrna(sampleInput)).toEqual(expected);
	});

	it('should pass test involving large numbers', () => {
		// tslint:disable:max-line-length
		const input =
			'MWIPWTGQITSQHAELRPSKMERPYYYPYCYDKNYTSQTIRIKFACQARKGMGRPSFWPNCLCQKLCDHLCNHFFRREGCVNFKFLDKLSDINLSSMYCIGEILITNLPFKTSQAMKQKCSQLESKFCYGNWEKRSYFDGDITAVEFFMIIMPRILCHGRYWGTQRANKILCGPEHEGKRVTTANIHTQINMTNLHVGLDYACYSTKTNIQCWVPCSHVMKLGHYLWMMWEGKFWNYTNDEYFDINQWVWANKWHVRAMNYPQIAMEMHAPCKQQPDNERHRGPNVYQKAMVHKIFAVKGKTHSAHKWIKNYGMGTYKMQKVFIETWTLNPLCQSYCWNSPMPAWVINWNHECASEEKWLCYCQETWPEEWPEWSYKCKNKLKMVTQPTYHIQKEDLHVWFMWFKDCSKLMCMEDSNLRFTTIEKSFNCMYMIHLPLCKWHGYEGFLTHLHPATDSEYPDWKGRPKPQAWAHEVPDIPSYKRGDLHQWARQAWLQVFKTLLKIRYWDWFFITRMLNGRNPMRYCNTNVIWGIPMEIHEPHAHSIVRACQTPMEWMRCWFALSLPFWTCHWYHFMMQGERERRKQGKEYCGSVESSCKPMQWWVGAHWPVPIPSHRAIHASFYWECFCKCLIHFNVAPVLAGSPHCFLWRCYACWTIKEMGCHDEKYCYASGKDFWLSMCEWEFRGMTAFPDGFSPWTQSKMMWITASFEQWSINMNDRDHFKHFMGWVGAIELFQDCYLMETRMPLMKGYQETNIGGLWCCGCVHQFVCCTDVFLVVMASWTRFTFVLMSQLREAIRHQVWPALGEDMMEFRDMDRITVSNMWLGLYWWQMVAAAMYHNPQHEEQYMMPTFHYSATISHAKSKEFCSWMMQWPEGMFLYKGQKSLFLQVMAMFKHSNVMISVGNLEPGHTNMAIAHFFPKGRGLSEMFDCVHSRCHDMIDWKYYTATEVRNNNADDSFNIEKIMIVYDTTYTNDFLFTVCMSKLVEWYYTTRINWTM';
		const expected = '667968';
		expect(mrna(input)).toEqual(expected);
	});
});
